---
- hosts: server 
  tasks:
    - name: Create production directory
      file: state=directory path=~/production

    - name: Upload Dockefile
      copy: src=prod-Dockerfile dest=~/production/Dockerfile
    
    - stat: path=~/production/M3-Deployment
      register: repo_exist
    
    - name: Git clone
      command: git clone https://github.com/DevOpsGHZ/M3-Deployment
      when: repo_exist.stat.exists == False
      args:
        chdir: ~/production

    - name: Git pull
      command: git pull
      when: repo_exist.stat.exists == True
      args:
        chdir: ~/production/M3-Deployment
    
   # - name: Tag the old image
   #   command: docker tag localhost:5000/sample:latest localhost:5000/sample:previous
   #   sudo: yes

   # - name: Build Dockerfile
   #   docker_image: path="/home/ubuntu/M3-Deployment" name="sample-app" state=build
   #   sudo: yes
    - name: Registry
      docker:
        name: registry
        image: registry:2
        ports:
          5000:5000
        docker_api_version: 1.18
      sudo: yes

    - name: Redis container
      docker:
        name: myredis
        image: redis
        command: redis-server --appendonly yes
        state: started
        expose:
          - 6379
        docker_api_version: 1.18
      sudo: yes

    - name: Build
      command: docker build -t sample-app .
      args:
        chdir: /home/ubuntu/production
      sudo: yes

    - name: Tag
      command: docker tag -f sample-app localhost:5000/sample:production
      sudo: yes
   
    - name: push
      command: docker push localhost:5000/sample:production
      sudo: yes

    - name: Route all traffic to staging app
      command: echo set route 2 | redis-cli -h 172.17.0.3

    - name: stop app
      command: docker rm -f app
      sudo: yes
      ignore_errors: yes

    - name: App
      docker:
        name: app
        image: localhost:5000/sample:production
        registry: localhost:5000
        state: restarted
        pull: always
        links:
          - "myredis:redis"
        ports:
          - 3001:3000
        docker_api_version: 1.18
      sudo: yes

    - name: Back to normal routing
      command: echo set route 1 | redis-cli -h 172.17.0.3
   # - name: run
   #   command: docker run -p 50100:8080 -d --name app localhost:5000/sample:latest
   #   sudo: yes 
