---
- hosts: all 
  tasks:
    - name: Install Git
      apt: pkg=git state=installed update_cache=true
      sudo: yes
    
    - name : Install curl
      apt: pkg=git state=installed update_cache=true
      sudo: yes

#    - name: Install docker
#      command: curl -sSL https://get.docker.com/ | sh
#      sudo: yes
    - name: Apt get update
      command: apt-get update
      sudo: yes
   
    - name: Install docker
      apt: pkg=docker.io state=installed update_cache=true
      sudo: yes

#    - name: start docker
#      command: service docker start
#      sudo: yes

    - name: Install pip
      apt: pkg=python-pip state=installed update_cache=true
      sudo: yes

    - name: install docker-py
      command: pip install docker-py
      sudo: yes

