---
- hosts: redis-server 
  tasks:
    - name: Install Git
      apt: pkg=git state=installed update_cache=true
      sudo: yes
    
    - name : Install curl
      apt: pkg=git state=installed update_cache=true
      sudo: yes

    - name: Apt get update
      command: apt-get update
      sudo: yes
   
#    - name: Install docker
#      apt: pkg=docker.io state=installed update_cache=true
#      sudo: yes

    - name: Install pip
      apt: pkg=python-pip state=installed update_cache=true
      sudo: yes

    - name: install docker-py
      command: pip install docker-py
      sudo: yes

    - name: Redis container
      docker:
        name: redis
        image: redis
        command: redis-server --appendonly yes
        state: started
        expose:
         - 6379
        docker_api_version: 1.18
      sudo: yes

    - name: stop ambassador
      command: docker rm -f redis_ambassador
      sudo: yes
      ignore_errors: yes
   
    - name: Start ambassador
      command: docker run -it -d -p 6379:6379 --link redis:redis --name redis_ambassador svendowideit/ambassador
      sudo: yes

#    - name: Redis ambassador
#      docker:
#        name: redis_ambassador
#        image: svendowideit/ambassador
#        pull: always
#        ports:
#         - 6379:6379
#        links:
#         - "redis:redis"
#        state: restarted
#        docker_api_version: 1.18
#      sudo: yes
